name: rpg-storefront-api

services:
  db:
    image: postgres:17.2-alpine3.21
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: testdb

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080